version: '3'
services:
  node_app:
    build: .
    container_name: node_app
    ports:
      - "3001:3001"
    restart: always

  nginx:
    image: nginx:alpine
    container_name: nginx_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    depends_on:
      - node_app
    restart: always
